# Site settings
title: RedRainCopper
header-img: "img/facebook.jpg"
tagline: "cn"  
description: "RedRainCopper|Think Different"  
baseurl: ""
url: "http://RedRainCopper.github.io"  

# About/contact
owner: 
  name: "RedRainCopper"
  email: RedRainCopper@gmail.com
  bio: ""

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
twitter_username: 
github_username: RedRainCopper
weibo_username: RedRainCopper
facebook_username:
zhihu_username: RedRainCopper

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
relative_permalinks: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "RedRainCopper"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : hanson
  disqus :
      short_name : hanson

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
